package com.atm.management.dto.response;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDate;
import java.time.LocalDateTime;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class NoticeResponse {
    private Long id;
    private String title;
    private String description;
    private String priority;
    private String createdBy;
    private LocalDateTime createdAt;
    private LocalDate expiryDate;
    private String invoiceStatus;
    private Long atmId;
    private String atmName;
    private String atmSerialNumber;
    private Boolean isAutoGenerated;
}
