package com.atm.management.service;

import com.atm.management.dto.request.NoticeRequest;
import com.atm.management.dto.response.NoticeResponse;
import com.atm.management.exception.ResourceNotFoundException;
import com.atm.management.model.Atm;
import com.atm.management.model.Notice;
import com.atm.management.repository.AtmRepository;
import com.atm.management.repository.NoticeRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.stream.Collectors;

@Service
@RequiredArgsConstructor
@Slf4j
@Transactional
public class NoticeService {

    private final NoticeRepository noticeRepository;
    private final AtmRepository atmRepository;

    /** Return every notice newest-first */
    @Transactional(readOnly = true)
    public List<NoticeResponse> getAllNotices() {
        return noticeRepository.findAllByOrderByCreatedAtDesc()
                .stream().map(this::toResponse).collect(Collectors.toList());
    }

    /** Return notices filtered by invoiceStatus */
    @Transactional(readOnly = true)
    public List<NoticeResponse> getByInvoiceStatus(String status) {
        return noticeRepository.findByInvoiceStatusOrderByCreatedAtDesc(status)
                .stream().map(this::toResponse).collect(Collectors.toList());
    }

    /** Create a manually posted notice */
    public NoticeResponse createNotice(NoticeRequest req) {
        Notice notice = new Notice();
        notice.setTitle(req.getTitle());
        notice.setDescription(req.getDescription());
        notice.setPriority(req.getPriority() != null ? req.getPriority() : "info");
        notice.setCreatedBy(req.getCreatedBy());
        notice.setExpiryDate(req.getExpiryDate());
        notice.setIsAutoGenerated(false);
        return toResponse(noticeRepository.save(notice));
    }

    /** Update invoice status (RAISED / NOT_RAISED / PENDING) */
    public NoticeResponse updateInvoiceStatus(Long id, String status) {
        Notice notice = noticeRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Notice not found: " + id));
        notice.setInvoiceStatus(status);
        return toResponse(noticeRepository.save(notice));
    }

    /** Delete a single notice */
    public void deleteNotice(Long id) {
        if (!noticeRepository.existsById(id)) {
            throw new ResourceNotFoundException("Notice not found: " + id);
        }
        noticeRepository.deleteById(id);
    }

    /** Flush all notices */
    public void flushAll() {
        noticeRepository.flushAll();
    }

    /** Flush only notices matching a given invoiceStatus */
    public void flushByStatus(String status) {
        noticeRepository.flushByInvoiceStatus(status);
    }

    /**
     * Auto-generate delivery notices for every ATM that has a delivery date
     * but does not yet have an auto-generated notice.
     * Safe to call repeatedly — idempotent.
     */
    public int syncDeliveryNotices() {
        List<Atm> atmsWithDelivery = atmRepository.findAll().stream()
                .filter(a -> a.getDeliveryDate() != null)
                .collect(Collectors.toList());

        int created = 0;
        for (Atm atm : atmsWithDelivery) {
            // Skip if a notice was already generated for this ATM (flag survives deletions)
            if (Boolean.TRUE.equals(atm.getNoticeGenerated())) {
                continue;
            }
            Notice notice = new Notice();
            notice.setTitle("Invoice Required - " + atm.getName());
            notice.setDescription(
                    "Asset \"" + atm.getName() + "\" (Serial: " + atm.getSerialNumber() + ") was delivered on "
                    + atm.getDeliveryDate() + ". Please raise an invoice for this delivery."
            );
            notice.setPriority("warning");
            notice.setCreatedBy("System");
            notice.setAtm(atm);
            notice.setIsAutoGenerated(true);
            notice.setInvoiceStatus("PENDING");
            noticeRepository.save(notice);
            // Mark ATM so this notice is never regenerated, even after deletion
            atm.setNoticeGenerated(true);
            atmRepository.save(atm);
            created++;
        }
        log.info("Delivery notice sync: {} new notice(s) created", created);
        return created;
    }

    private NoticeResponse toResponse(Notice n) {
        NoticeResponse r = new NoticeResponse();
        r.setId(n.getId());
        r.setTitle(n.getTitle());
        r.setDescription(n.getDescription());
        r.setPriority(n.getPriority());
        r.setCreatedBy(n.getCreatedBy());
        r.setCreatedAt(n.getCreatedAt());
        r.setExpiryDate(n.getExpiryDate());
        r.setInvoiceStatus(n.getInvoiceStatus());
        r.setIsAutoGenerated(n.getIsAutoGenerated());
        if (n.getAtm() != null) {
            r.setAtmId(n.getAtm().getId());
            r.setAtmName(n.getAtm().getName());
            r.setAtmSerialNumber(n.getAtm().getSerialNumber());
        }
        return r;
    }
}
