import api from '@/lib/api';

export type InvoiceStatus = 'PENDING' | 'RAISED' | 'NOT_RAISED';
export type NoticePriority = 'info' | 'warning' | 'critical' | 'resolved';

export interface NoticeResponse {
  id: number;
  title: string;
  description: string;
  priority: NoticePriority;
  createdBy: string;
  createdAt: string;
  expiryDate?: string;
  invoiceStatus: InvoiceStatus;
  atmId?: number;
  atmName?: string;
  atmSerialNumber?: string;
  isAutoGenerated: boolean;
}

export interface NoticeRequest {
  title: string;
  description: string;
  priority: NoticePriority;
  createdBy: string;
  expiryDate?: string;
}

export const noticeService = {
  getAll: async (): Promise<NoticeResponse[]> => {
    const res = await api.get('/notices');
    return res.data;
  },

  create: async (req: NoticeRequest): Promise<NoticeResponse> => {
    const res = await api.post('/notices', req);
    return res.data;
  },

  updateInvoiceStatus: async (id: number, invoiceStatus: InvoiceStatus): Promise<NoticeResponse> => {
    const res = await api.patch(`/notices/${id}/invoice-status`, { invoiceStatus });
    return res.data;
  },

  deleteNotice: async (id: number): Promise<void> => {
    await api.delete(`/notices/${id}`);
  },

  flushAll: async (): Promise<void> => {
    await api.delete('/notices/flush');
  },

  flushByStatus: async (status: InvoiceStatus): Promise<void> => {
    await api.delete(`/notices/flush/${status}`);
  },

  syncDelivery: async (): Promise<{ created: number }> => {
    const res = await api.post('/notices/sync-delivery');
    return res.data;
  },
};
