package com.atm.management.repository;

import com.atm.management.model.Notice;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Optional;

@Repository
public interface NoticeRepository extends JpaRepository<Notice, Long> {

    List<Notice> findAllByOrderByCreatedAtDesc();

    List<Notice> findByInvoiceStatusOrderByCreatedAtDesc(String invoiceStatus);

    // Check if an auto-generated notice already exists for a given ATM
    Optional<Notice> findByAtmIdAndIsAutoGeneratedTrue(Long atmId);

    // Delete all notices
    @Modifying(clearAutomatically = true, flushAutomatically = true)
    @Query("DELETE FROM Notice n")
    void flushAll();

    // Delete all notices by invoice status
    @Modifying(clearAutomatically = true, flushAutomatically = true)
    @Query("DELETE FROM Notice n WHERE n.invoiceStatus = :status")
    void flushByInvoiceStatus(String status);
}
